### ISSUE TITLE
Aliasing latest

### ISSUE THREAD

**Issue by passcod** [onur/docs.rs#1]
It would be nice to have aliasing (through the use of, say, symlinks) for the latest version, so we could point the README of a project to https://crates.fyi/crates/cratename/latest/.

**Comment by onur** [comment]
This is the first thing in my TODO. I am trying to catch crates.io-index atm. There are 30 crates in que. Building google-* crates taking too much time.

**Comment by passcod** [comment]
As an addendum, although I'm not sure of the use, version aliasing like 3 -> latest 3.x.y version and 3.2 -> latest 3.2.x could be useful for libraries that maintain multiple branches/versions.

**Comment by icorderi** [comment]
Hey, was about to ask for this feature.
Bump it up! +1

@passcod makes an interesting point.@onur have you thought about a `.cratesfyi` configuration file where we can say `3.x.y = branch/name`. That would address @passcod requirement and gives people the ability to control aliases from their own repo.

**Comment by passcod** [comment]
@icorderi I believe crates.fyi builds from crates.io, not github, so the concept of branch names doesn't apply.

**Comment by reem** [comment]
Yeah I would love a "latest" tag, would be really nice to just be able to stick a latest docs link in the README of every project and never worry about it again.

**Comment by onur** [comment]
Adding sources other than crates.io is in my TODO but I am planning to support only crates released into crates.io for now. cratesfyi may fetch (or listen) crate repository and generate doc from a specific branch in future.
