### ISSUE TITLE
Allow crates to specify which features to build for documenting purposes

### ISSUE THREAD

**Issue by nox** [onur/docs.rs#102]
docs.rs could use a [metadata table](http://doc.crates.io/manifest.html#the-metadata-table-optional) key to be taught about which features to use when generating the docs. For example, `simd` has a [feature](https://github.com/rust-lang-nursery/simd/blob/master/Cargo.toml#L25) that enables everything in the crate, so that the documentation isn't platform-dependant.

**Comment by nox** [comment]
Oh, that seems to be #73...

**Comment by mathstuf** [comment]
@nox I think this can be closed.

**Comment by onur** [comment]
Yes docs.rs supports building non-default features and metadata.
