### ISSUE TITLE
The requested resource does not exist

### ISSUE THREAD

**Issue by rushmorem** [onur/docs.rs#103]
For some reason, some crates on docs.rs are coming up with this error message. This used to be a mystery to me but now even one of my own crates is returning this error for the latest version. Right now docs for [v0.0.6-alpha2](https://docs.rs/reql/0.0.6-alpha2/reql/) are running into this error while those for [v0.0.6-alpha1](https://docs.rs/reql/0.0.6-alpha1/reql/) and below are fine.

**Comment by onur** [comment]
@rushmorem looks like v0.0.6-alpha2 [failed to build](https://docs.rs/crate/reql/0.0.6-alpha2/builds/41328). Some package also failed with same error message. I am not sure what is causing this. Maybe you can help, did you change any dependency in new version?

**Comment by rushmorem** [comment]
I had a hunch this might be the problem. This log confirms that. The thing is `reql-io` is an implementation detail for `reql` . It depends on `reql` for some datatypes. However, to make it easier for users, `reql` also depends on `reql-io` to reexport it. Cargo doesn't seem to have a problem with this. However, thanks to this issue, I'm now working on a better design which should work on `docs.rs`.

I'm going to leave this issue open in case someone wants to try and fix this. @onur If docs.rs is working as intended here, feel free to close this issue.

**Comment by onur** [comment]
I believe docs.rs is working as intended. I tried to run example code in README:

```rust
extern crate reql;

use reql::r;

fn main() {
    r.connection().connect().expect("Failed to connect to the database server");
}
```

with `reql = "0.0.6-alpha2"` dependency I am getting same error:

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: cyclic package dependency: package `reql v0.0.6-alpha2` depends on itself
```

And `v0.0.6-alpha3` is working fine. Docs.rs should build this package without any issue (it's in queue right now).
