### ISSUE TITLE
Update rustc version.

### ISSUE THREAD

**Issue by Aaronepower** [onur/docs.rs#11]
Currently `cratesfyi` is using a much older version of rustc, and so some projects which rely on those features aren't working. 
[Example](https://crates.fyi/logs/tokei/tokei-3.0.0.log)

**Comment by onur** [comment]
Thanks for reporting, cratesfyi is using `rustc 1.11.0-nightly (0554abac6 2016-06-10)` now. But it is using old rustdoc.css from 1.8. New version of cratesfyi will fix this issue.

**Comment by onur** [comment]
I am closing this issue since it was only exists in old versions of cratesfyi.
