### ISSUE TITLE
Exact match should rank higher

### ISSUE THREAD

**Issue by bluss** [onur/docs.rs#111]
[Search for `ndarray` ](https://docs.rs/releases/search?query=ndarray) or [search for `glium`](https://docs.rs/releases/search?query=glium) has the crate of that name as the 8th/6th result; I'd expect it to be 1st/1st since it's an exact match.

(For moz keyword purposes [or other searching] I'm wondering if there's an equivalent search link that goes directly to the crate if it's an exact match.  Wikipedia has that kind of thing: https://en.wikipedia.org/wiki/Special:Search?go=Go&search=Rust where it either goes to the exact match or to search results.)

**Comment by bluss** [comment]
[Search for matches](https://docs.rs/releases/search?query=matches), the crate `matches` is not even in the search results.

**Comment by onur** [comment]
Currently crate names have higher weight in results but search is also looking for root crate doc and/or README. Crates listed in `matches` results have tons of `match` in their root crate doc, that is why they are showing up first. I think removing looking for root crate doc and README will definitely help this issue.

**Comment by bluss** [comment]
What do you think about using some kind of additional order by clause (not to replace order by rank, but to order both by string comparison and rank). Something along the lines of https://stackoverflow.com/a/45139557/  Is it viable, or too ugly of a solution?
