### ISSUE TITLE
Broken link pointing to seemingly implementation details instead of public interface of a target crate

### ISSUE THREAD

**Issue by vi** [onur/docs.rs#123]
https://docs.rs/tokio-core/0.1.7/tokio_core/reactor/struct.PollEvented.html#methods has broken link "[Evented](https://docs.rs/mio/0.6.1/mio/event_imp/trait.Evented.html)" which should probably actually go to https://docs.rs/mio/0.6.1/mio/trait.Evented.html

**Comment by dtolnay** [comment]
Thanks @vi. This seems like a rustdoc bug rather than a docs.rs bug, because the same thing happens in a local `cargo doc` of tokio-core. Please check whether there is an existing rustdoc issue about this and create one if there is not.

**Comment by onur** [comment]
I think this issue is fixed in the latest versions of rust compiler (or maybe #131 fixed it). `Evented` link is working as expected now.
