### ISSUE TITLE
Clicking Structs/Enums link in sidebar results in blank page and "undefined" in search box

### ISSUE THREAD

**Issue by robinst** [onur/docs.rs#126]
Hey! First off, awesome service! I just published my first crate and noticed a small problem. Here's how to reproduce:

1. Go here: https://docs.rs/linkify/0.1.0/linkify/
2. Click on "Structs" in the side bar

Expected: It shows the structs of the crate
Actual: See screenshot, "undefined" is put into the search box and the page is blank

<img width="811" alt="screen shot 2017-05-18 at 11 41 42" src="https://cloud.githubusercontent.com/assets/16778/26182960/00cb3e26-3bbf-11e7-92c1-87568f73b046.png">

This is in Firefox, but I can reproduce it on Chrome as well.

**Comment by onur** [comment]
Thanks for reporting. That was a bug in nightly, updating nightly fixed the issue.

**Comment by robinst** [comment]
Cool, thanks!
