### ISSUE TITLE
docs.rs does not produce documentation for sub-crates

### ISSUE THREAD

**Issue by Marwes** [onur/docs.rs#128]
In [gluon](https://docs.rs/gluon/0.4.0/gluon/) I have a main `gluon` crate which serves as the easy to use interface for a few different sub-crates. These re-exports do not get links however which makes the documentation rather difficult to browse https://docs.rs/gluon/0.4.0/gluon/#reexports which I suppose is because docs.rs only builds documentation for the crate in question. It might do this for a good reason but would it be possible to at least get documentation built and linked for publicly re-exported crates as well?

**Comment by onur** [comment]
Thanks for reporting. This is a limitation of docs.rs and I am working on a solution.

Currently you can define `#![doc(html_root_url="https://docs.rs/$crate/$version")]` as described in [rust-api-guidelines](https://github.com/brson/rust-api-guidelines#c-html-root) in all your crates to make it work.

**Comment by Marwes** [comment]
Awesome! I will try to add the root_url and make a new release. Thanks!

**Comment by Marwes** [comment]
That did the trick https://docs.rs/gluon/0.4.2/gluon/ !

**Comment by onur** [comment]
#131 also fixed this issue, you no longer need to set `html_root_url`, docs.rs will do this automatically for all crates and it's dependencies.
