### ISSUE TITLE
Re-enable MSVC target

### ISSUE THREAD

**Issue by Boddlnagg** [onur/docs.rs#135]
In a [comment](https://github.com/onur/docs.rs/pull/131#issuecomment-306867152) you said that ...

> ... if I am not mistaken a windows-gnu host can build windows-msvc targets and it should be easy to add windows-msvc target. I'll add windows-msvc target again when I am free.

Since there seemed to be no issue tracking that, I thought I'd create one. I think this is important because some Windows crates can't build for the MinGW target and [MSVC is the preferred target](https://github.com/onur/docs.rs/pull/131#issuecomment-306836259) anyway.

**Comment by onur** [comment]
Thanks for reporting. I'll add MSVC windows targets again with the next rustc update. I've got some issues building rust compiler for the all tier one platforms, hopefully I'll fix it in the next few days.

**Comment by onur** [comment]
Alright, I re-enabled MSVC targets, sorry it took me awhile to figure out right build tools for compiling rustc msvc targets (unfortunately I tried many). For the future reference: [Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) is the right toolset for building rustc msvc targets.
