### ISSUE TITLE
Styling: emphasis of functions vs subheadings

### ISSUE THREAD

**Issue by SDEagle** [onur/docs.rs#151]
Hello everybody,

while using the rust docs and other crates docs there is always one stylistic issue that is troubling me a bit. The subheadings in the documentation of each function are visually much more emphasized than the actual function. And that makes reading through the docs and for example searching for a function pretty hard because my eyes always jump to `Examples` `Examples` `Examples` `Examples`...

This screenshot is taken from zeal (offline doc browser, linux clone for dash), and demonstrates the issue quite nicely. 
![screenshot from 2017-08-30 10-44-39](https://user-images.githubusercontent.com/867049/29863933-78c17f40-8d71-11e7-87c7-6464fd72ea3d.png)
 In the online docs it's slightly better, but still hard.

So I was wandering, is this actually intended? Or could we maybe improve the styles to visually put more emphasis on the functions?

**Comment by onur** [comment]
Hi, thanks for reporting but this has nothing to do with docs.rs and a design choice made by rust-docs team and documentation creators of standard library. You can contact them in #rust-docs on [IRC](https://wiki.mozilla.org/IRC) or you can open an issue report on [rust-lang/rust](https://github.com/rust-lang/rust) repository instead.
