### ISSUE TITLE
How to link to latest version?

### ISSUE THREAD

**Issue by andreastt** [onur/docs.rs#153]
I’m sorry in advance if this is not the right forum for a question about docs.rs.

docs.rs provides a convenient way of linking types in documents such as [change logs](https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md) to API documentation, but I quite often want to link to the latest version of the type.

For example with https://docs.rs/webdriver/0.30.0/webdriver/error/enum.ErrorStatus.html, being able to replace `0.30.0` with `latest`, which would redirect you to the latest version of the documentation would be useful so that one wouldn’t have to revisit documentation to update the links when a new version becomes available.

**Comment by onur** [comment]
You can use [`newest`](https://docs.rs/webdriver/newest/webdriver/error/enum.ErrorStatus.html) (someone suggested this earlier, `latest` seems more reasonable) or [`*`](https://docs.rs/webdriver/*/webdriver/error/enum.ErrorStatus.html) for the version. This currently have some sort of browser cache issue but I'll redirect this requests to actual latest version in future, so it should be ok.

**Comment by crumblingstatue** [comment]
`newest` doesn't seem to work when linking to the source code.

https://docs.rs/crate/sfml/newest/source/examples/ just shows an empty page.

I wanted to use this as a workaround for #132.

**Comment by onur** [comment]
Yeah, looks like source tab is not semver compatible. I was planning to improve source browser, this feature also needs to be added.

**Comment by andreastt** [comment]
This is great, thanks everyone!
