### ISSUE TITLE
Long lines of code break the layout

### ISSUE THREAD

**Issue by dns2utf8** [onur/docs.rs#162]
Hi there

I noticed a bad layout [on this page](https://docs.rs/clap/2.26.2/clap/) in the macro section if the windows with is small enough, the table for the macros is to wide and the browser starts to scroll to the side:

![image](https://user-images.githubusercontent.com/739070/31634555-40c125be-b2c4-11e7-9a74-6e12540e3957.png)

Responsible in this case it the following element:
```html
<code>"author1 lastname &lt;author1@example.com&gt;:author2 lastname &lt;author2@example.com&gt;"</code>
```
combined with this css:
```css
.docblock-short code {
    white-space: nowrap;
}
```

A solution would could be to scroll the block or to linewrap the code and mark the inserted linewraps with a for example red `↵` symbol and maybe add linenumbers.

PS: If this is not the right place for the issue, please point me in the right direction

**Comment by onur** [comment]
Thanks for reporting. This is caused by `rustdoc` and you can report `rustdoc` issues into [rust-lang/rust](https://github.com/rust-lang/rust) repository.
