### ISSUE TITLE
Support /cratename/latest as alias for newest version

### ISSUE THREAD

**Issue by theduke** [onur/docs.rs#169]
Maintaining links to `docs.rs` documentation is quite annoying since, as far as I can tell, there is no way to reference the latest version by url.

eg: Let's say I want to link to documentation for a certain type like https://docs.rs/diesel/1.0.0-beta1/diesel/pg/struct.Pg.html. I have to update that link every time a new version is released, which can be done automatically sometimes, but also can be cumberosme in some situations.

It would be great to have an alias like , for the example above: ttps://docs.rs/diesel/latest/diesel/pg/struct.Pg.html, where `latest` is recognized as an alias for the newest released version.

**Comment by onur** [comment]
You can use `newest` (someone else suggested this earlier, I'll add `latest` alias as well) or `*` since all versions are semver compatible for the latest version of documentation.

https://docs.rs/diesel/newest/diesel/pg/struct.Pg.html
https://docs.rs/diesel/*/diesel/pg/struct.Pg.html

**Comment by theduke** [comment]
Ah, great!

It would probably be smart to add that to the `Redirects` section at https://docs.rs/about.
