### ISSUE TITLE
Use all features for building the docs

### ISSUE THREAD

**Issue by vityafx** [onur/docs.rs#180]
It would be quite nice if we knew all the available methods and see them documented. For example, the `chrono` crate has its docs published but the docs does not mention the `from_ts` method which is not visible if we use default features, we should use "serde" feature for that. So I propose to build crates with all available features to have documentation about all of it.

**Comment by retep998** [comment]
You can already select which features to enable when built by docs.rs.
```toml
[package.metadata.docs.rs]
features = ["foo", "bar"]
```

**Comment by retep998** [comment]
Nope, which is a known issue in and of itself: https://github.com/onur/docs.rs/issues/148

**Comment by vityafx** [comment]
Nice. Then this can be closed.
