### ISSUE TITLE
docs.rs link to nightly docs is broken

### ISSUE THREAD

**Issue by icefoxen** [onur/docs.rs#181]
On this function: https://docs.rs/ggez/0.4.0/ggez/timer/fn.get_delta.html

The link to the `Duration` type aims at `https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html` but the proper link is at `https://doc.rust-lang.org/nightly/std/time/struct.Duration.html`.

It looks like the organization for `docs.rust-lang.org` has changed out from underneath us slightly in a recent revision...  On stable the first URL format works fine.  Not sure whether this is a bug in rustdoc or not.

**Comment by sfleischman105** [comment]
It seems nightly docs.rs has been broken for a while, see #171 .
