### ISSUE TITLE
method listing of a struct or enum not shown

### ISSUE THREAD

**Issue by ajjaic** [onur/docs.rs#183]
I'm not sure If I'm viewing the page wrong or something, here are my observations.

In the documentation for the std library, when we browse the page for a struct or an enum, it's methods are neatly listed on the side bar. This greatly helps when we just want to skim through the set of methods supported by that struct or enum.

But on docs.rs, I'm not sure if it is happening for every crate, but on the crate I am on(`orca`), I'm viewing the struct `orca::App` and it has a long list of methods it supports. But on the side bar, I do not see the method list. There is no `skimming` through the method list due to this. 

Could someone please tell me, if this requires a fix (perhaps I can fix it myself and create a PR) or if this can be dealt with as it is, through some setting or the other? Or is the crate author responsible for adding certain elements in the source to auto-generate the method list.

**Comment by onur** [comment]
Hi, and thanks for reporting. That feature is been added in the recent versions of rustdoc and currently docs.rs is using an old version. I am so close to update rustc on docs.rs and hopefully this issue will be fixed in a few days.
