### ISSUE TITLE
Support for setting RUSTFLAGS?

### ISSUE THREAD

**Issue by tarcieri** [onur/docs.rs#185]
I'm using a [stdsimd-dependent crate](https://crates.io/crates/aesni) which needs special `RUSTFLAGS` in order to compile. Because these flags are unset, docs.rs fails to build my crate:

https://docs.rs/crate/yubihsm/0.1.0/builds/90580

This seems more like an ergonomics problem with Rust itself than with docs.rs specifically, however if there were a way to set at least `target-feature` in `RUSTFLAGS` that would be enough to fix my docs builds.

**Comment by gnzlbg** [comment]
docs.rs generates docs for all the tier-1 targets, but your crate does not compile in any of the tier-1 targets. 

While adding support for generating docs for other targets in docs.rs would be cool, the fact that your crate does not compile on any tier-1 target is entirely your own fault.

**Comment by onur** [comment]
@tarcieri you can set `RUSTFLAGS` by setting `rustc-args` in your Cargo.toml like this:

```toml
[package.metadata.docs.rs]
rustc-args = [ "--example-rustc-arg" ]
```

This is actually setting `RUSTFLAGS` (sinde docs.rs is never calling rustc on main crate, it is passing `rustc-args` as `RUSTFLAGS` for other dependencies).

**Comment by tarcieri** [comment]
@onur that worked! Thanks!

Or rather, it got me farther along. It doesn't look like the nightly docs.rs is using is new enough to support `core::arch`:

https://docs.rs/crate/yubihsm/0.1.1/builds/90719

I'll call that "good enough to close the issue" at least

**Comment by onur** [comment]
@tarcieri I am waiting few PR's to get merged, I'll update rustc again in couple of days.

**Comment by tarcieri** [comment]
@onur great, thanks!

**Comment by gnzlbg** [comment]
@onur would it be possible to document this in the about page of docs.rs ? And also, how to control for which targets the docs are generated?

**Comment by onur** [comment]
@gnzlbg yes I will document this feature in about page and currently you can't control targets, docs.rs will try to build crate for rust's tier 1 platforms (Linux, OSX, Windows).

**Comment by gnzlbg** [comment]
>  and currently you can't control targets, docs.rs will try to build crate for rust's tier 1 platforms (Linux, OSX, Windows).

Maybe it would be good to document that too, like which targets exactly, and what happens when one target fails to build, etc.

**Comment by onur** [comment]
@gnzlbg yes I agree, unfortunately docs.rs lacks some documentation, I'll hopefully improve it a bit this week. You can see supported targets in [here](https://github.com/onur/docs.rs/blob/8a31bf722cb416fec86866e3dd54ba59762e31fa/src/docbuilder/chroot_builder.rs).
