### ISSUE TITLE
Certain crates are missing.

### ISSUE THREAD

**Issue by ticki** [onur/docs.rs#2]
rs-tiled for example.

**Comment by onur** [comment]
Yes currently some crates are missing. Looks like [tiled](https://crates.io/crates/tiled) failed to build on `rustc 1.8.0-nightly (d63b8e539 2016-01-23)`. You can see build log in here: <http://build.crates.fyi:3180/logs/tiled/tiled-0.1.4.log>

Build machine is using an old version of cratesfyi and rustc atm, I can't update rustc atm (it's been trying to build everything since I announced this project). And cratesfyi changed alot. I am preparing a huge update, hang on few more weeks.

**Comment by Ticki** [comment]
I fixed Tiled a couple of days ago. A rebuild should success.

**Comment by JonasOlson** [comment]
For [`physical_constants`](https://crates.io/crates/physical_constants), I don't even find a log, actually.

**Comment by onur** [comment]
@JonasOlson the version docs.rs running in https://crates.fyi/ is stopped working.

New beta version (https://beta.docs.rs/) started building crates on 2016-07-30 and finally finished building all crates up to this date. And now it is building crates released between 2016-07-30 and today. Give it a few days and you will see your crate in beta.

**Comment by JonasOlson** [comment]
Sorry, I didn't notice that your log link actually pointed to `crates.fyi`. I thought it pointed to `docs.rs`.

Anyway, I saw that the counter on https://beta.docs.rs/ had reached 100%, so I thought everything would be there now.

**Comment by onur** [comment]
It's around 96% now, I removed counter today. We are getting there :smiley:

**Comment by JonasOlson** [comment]
Oh, I see! Is it possible to see build logs on `docs.rs`? (I don't know if`physical_constants` will build, since the version on `crates.io` calls a Python script.)

**Comment by onur** [comment]
Since docs.rs hasn't tried to build physical_constants, there is no log about it.

I tried to build physical_constants on docs.rs running on my local machine and it is building fine.

**Comment by onur** [comment]
@JonasOlson looks like docs.rs built your crate few hours ago: https://beta.docs.rs/physical_constants

**Comment by JonasOlson** [comment]
Nice. Are there build logs to be seen somewhere? (Not that I need it now, but it could be of interest in the future.)

**Comment by onur** [comment]
We had a "Builds" tab but I decided to remove it (kinda useless), but you can see build logs in here: https://beta.docs.rs/crate/physical_constants/0.1.1/builds

This link is only visible if docs.rs failed to build a crate.

**Comment by JonasOlson** [comment]
Thank you!

**Comment by onur** [comment]
Docs.rs have every crate now (except yanked ones).
