### ISSUE TITLE
New crates not updating on 7-may-2018

### ISSUE THREAD

**Issue by asomers** [onur/docs.rs#202]
On 6-may-2018 at about 22:00 UTC docs.rs stopped building new releases.  If you look at the main page, https://docs.rs/ , the most recent updates are all a little more than 24h old.

**Comment by onur** [comment]
opps sorry guys I forgot to remove lock file during maintenance, it should start building crates now :(

**Comment by onur** [comment]
@asomers it's still building crates, you can see the queue in here: https://docs.rs/releases/queue

Give it a bit time, recenlty released crates have higher priority in queue.

**Comment by asomers** [comment]
Are you sure it's not hung again?  The queue has not changed for > 30 minutes.

**Comment by onur** [comment]
No it's not @asomers. Building 300+ crate for 8 platform is a bit time consuming. It will eventually catch up crates.io.
