### ISSUE TITLE
Markdown Reference Links are Broken

### ISSUE THREAD

**Issue by SShrike** [onur/docs.rs#21]
The Markdown reference style link syntax seems to not be recognised by whatever you use for crate information page (where the README is displayed).

A Markdown reference style link looks like this:

```
[I'm a reference-style link][link]

[link]: example.org
```

This issue breaks README's like [mine](https://beta.docs.rs/crate/tutil/0.1.1).

**Comment by onur** [comment]
I believe this is an issue in pulldown-cmark.

I'll try hoedown (rustdoc's markdown renderer), hopefully it will be better.

**Comment by SShrike** [comment]
Thanks, I believe it does work with hoedown, since reference style links work in Rustdoc.

Maybe filing an issue an pulldown-cmark might also be appropriate? It seems like an important thing to be missing.

**Comment by SShrike** [comment]
It also seems that pulldown-cmark doesn't support GFM tables. See the README I linked in the issue body for an example.

**Comment by polyfractal** [comment]
Perhaps related, links to images in the repo are also broken:

```
![Sync Chan Threaded PDF](/sync_chan_threaded_pdf.png)
```

An example: [Docs.rs](https://docs.rs/crate/bounded-spsc-queue/0.1.2) vs [Github](https://github.com/polyfractal/bounded-spsc-queue/blob/master/README.md).  Maybe it's the same issue?

**Comment by onur** [comment]
I believe markdown renderer is much better now.

@polyfractal image serving is a different issue, and I don't know if I can fix it but I'll try to look into it.

**Comment by SShrike** [comment]
The renderer seems to be choking on the table in my README now.

**Comment by onur** [comment]
Yes tables doesn't have any css, I'll fix it.

**Comment by SShrike** [comment]
Thanks :)

**Comment by onur** [comment]
@SShrike I added some CSS to tables (similar to tables in about page).

**Comment by SShrike** [comment]
Looks great, just seems to be one small issue left.
![capture3](https://cloud.githubusercontent.com/assets/4061736/18147596/847bd9c2-7029-11e6-9a72-2fc7ab3097ff.PNG)

Seems to be an erroneous | for some reason.
