### ISSUE TITLE
Top bar for choosing crate version / platform no longer appears

### ISSUE THREAD

**Issue by Arnavion** [onur/docs.rs#210]
https://github.com/onur/docs.rs/commit/4a9cb42b4c9ea8d24e0eaf51290419889117aa03 removed the top bar that allows you to choose a crate version / platform / see other info about the crate.

Maybe you can use this issue to track bringing it back when you figure out the solution to the rustdoc changes?

**Comment by onur** [comment]
I'll try to bring it back this weekend.

@pravic new rustdoc changes did break entire top bar, I had no other choice. I'll try a different approach this time.

And yes, @GuillaumeGomez is always breaking docs.rs :-)

**Comment by GuillaumeGomez** [comment]
:-°

**Comment by pftbest** [comment]
Another use case for top bar is for browsing source code. Sometimes "Repository" link on crates.io points to a different version of the code compared to what is published, and you want to see the original. Also I was using this feature to look at `Cargo.toml` file to see what cargo features are available.

**Comment by spacekookie** [comment]
@onur Has there been any development on this?

**Comment by FaultyRAM** [comment]
As a workaround, you can manually navigate to the pages that the top bar linked to. Using winapi as an example:

https://docs.rs/crate/winapi/ displays the README for the latest version
https://docs.rs/crate/winapi/0.3.5/ displays the README for 0.3.5
https://docs.rs/crate/winapi/0.3.5/source/ lets you browse the source code for 0.3.5
https://docs.rs/winapi/0.3.5/x86_64-pc-windows-msvc/winapi/ displays target-specific documentation for 0.3.5

**Comment by QuietMisdreavus** [comment]
This should be fixed by https://github.com/onur/docs.rs/pull/217 now!
