### ISSUE TITLE
Is there a reason not to use stable Rust?

### ISSUE THREAD

**Issue by sgrif** [onur/docs.rs#211]
Diesel currently fails to compile on Rust nightly due to a bug in Rust. I fully suspect that this will be resolved before the current version becomes stable, but I really didn't expect this to cause the docs.rs build to fail. Is there a reason that docs.rs isn't using the normal, distributed, stable version of Rust?

**Comment by QuietMisdreavus** [comment]
Docs.rs uses a custom-patched rustdoc (right now i think the only patch is to redirect cross-crate links, but i could be wrong), so it requires having master to do that. I also imagine there are nightly-only crates that appreciate being able to distribute docs via docs.rs, and much fewer crates in diesel's situation.

**Comment by sgrif** [comment]
Makes sense. Thanks!
