### ISSUE TITLE
Crate API discoverability

### ISSUE THREAD

**Issue by akatechis** [onur/docs.rs#241]
Not sure if this is a very useful feature, but I'm currently experimenting with a crate and trying to learn exactly how to use it, and I think a great feature might be if I'm looking at the documentation for a struct, to be able to find functions that return the type I'm looking at, and/or accept the type as a parameter in some form (perhaps even as a parameterized type of a container, eg a function that accepts `Vec<T>` while I'm looking at the docs for `T`).

**Comment by memoryruins** [comment]
I agree; it's very useful while grokking a crate. Rustdoc supports this, and it works on docs.rs. After typing into the search bar, three tabs appear for searching by name, parameter, and return types. 

![paddr](https://user-images.githubusercontent.com/6868531/46909079-ceb64e00-cefa-11e8-9263-66d4f121e179.png)

**Comment by akatechis** [comment]
Oh my, can't believe I missed that! :) I will close this, then. Thanks!

**Comment by Havvy** [comment]
Can you open a new issue with the images?
