### ISSUE TITLE
The "I'm feeling lucky" button returns an error

### ISSUE THREAD

**Issue by achanda** [onur/docs.rs#25]
<img width="1672" alt="screen shot 2016-08-26 at 3 08 16 pm" src="https://cloud.githubusercontent.com/assets/2165463/18021843/0462a358-6b9f-11e6-971f-e9178d0bd387.png">

Looks like it should return a random crate

**Comment by onur** [comment]
There is no default behavior for that button. You need to type a crate name into search box before pressing "I'm feeling lucky".

**Comment by achanda** [comment]
I see. Closing the bug then.

**Comment by onur** [comment]
I think this is actually a bug, many people pressing that button without any search parameter.

Error message needs to be more descriptive.
