### ISSUE TITLE
Linkify bare URLs

### ISSUE THREAD

**Issue by Wilfred** [onur/docs.rs#40]
I've noticed that my README contains the following markdown:

```markdown
* http://mearie.org/projects/esotope/bfc/
* http://calmerthanyouare.org/2015/01/07/optimizing-brainfuck.html
* [http://xn--2-umb.com/10/brainfuck-using-llvm](http://xn--2-umb.com/10/brainfuck-using-llvm)
```

On GitHub, this gives me three links, but on docs.rs, only the third bullet is rendered as an anchor tag.

Link to the readme: https://docs.rs/crate/bfc

**Comment by onur** [comment]
Thanks for reporting, I wanted to make sure github is automatically converting links before using [AUTOLINK](https://docs.rs/hoedown/5.0.0/hoedown/constant.AUTOLINK.html) extension. Looks like we need it.
