### ISSUE TITLE
README detection

### ISSUE THREAD

**Issue by onur** [onur/docs.rs#42]
Currently, docs.rs is looking for `readme` field in `Cargo.toml` to find out if a crate contains any readme. But looks like many crates have README's in their root directory but doesn't have any `readme` field in `Cargo.toml`.

docs.rs should automatically detect readmes instead of trusting crate owner.

**Comment by bluss** [comment]
please find README.rst and so on too (various github-recognized extensions).

**Comment by onur** [comment]
There is a [rst](https://docs.rs/rst) crate but I am not sure if it is usable.

**Comment by SShrike** [comment]
Another format would be AsciiDoc READMEs.

**Comment by bluss** [comment]
Oh, rendering too of course, didn't think about that. I'd show README.rst without rendering until some solution could be found. If you can, I'd use the python doctools to render it, rst is quite bad with third party implementations.
