### ISSUE TITLE
Markdown rendering issues with underscores_in_names

### ISSUE THREAD

**Issue by joshtriplett** [onur/docs.rs#43]
See https://docs.rs/crate/clippy/0.0.88 for an example, and compare to https://github.com/Manishearth/rust-clippy .  In the latter, names like `block_in_if_condition_expr` show up correctly.  docs.rs interprets the underscores as markup for italics, italicizing the `in` and the `condition`.

This likely represents a difference in markdown dialect from what most packages expect.

**Comment by onur** [comment]
Thanks for reporting!
