### ISSUE TITLE
Default crate version should be highest version, not most recent released

### ISSUE THREAD

**Issue by shssoichiro** [onur/docs.rs#47]
For example: `iron-0.3.1` was released more recently than `iron-0.4.0`. Therefore, the default version linked to on docs.rs is 0.3.1, when the highest version is actually 0.4.0. It would make more sense to default to the highest version number.

**Comment by onur** [comment]
I believe this issue is fixed since docs.rs started using semver for matching versions. It is now returning greatest version instead of most recent one.
