### ISSUE TITLE
Broken links in rustdoc shown instead of README

### ISSUE THREAD

**Issue by sinkuu** [onur/docs.rs#49]
For example, clicking links for traits in https://docs.rs/crate/eclectic/0.10.0 will result in `The requested crate does not exist`.

**Comment by SShrike** [comment]
You can use semantic versioning ranges in the URL, so to create a URL that always pointed to, for example the latest `eclectic::Collection`, you would create a URL like this: https://docs.rs/eclectic/*/eclectic/trait.Collection.html.

**Comment by onur** [comment]
Problem is docs.rs is getting README from crates root documentation if there is no `readme` defined in `Cargo.toml`. This issue will be fixed with #42.
