### ISSUE TITLE
Set a specific feature during doc generation

### ISSUE THREAD

**Issue by dflemstr** [onur/docs.rs#50]
Use case: if your library depends on some native library or otherwise does something funky during build, it won't be exposed on `docs.rs`.

The build could check for the presence of a `docs` feature in the `Cargo.toml` file, for example like this:

```
cargo read-manifest | rq 'select"$.features"|map(o)=>{_.keys(o)}|spread|some(x)=>{"docs"==x}'
```

(Shameless plug: [rq](https://github.com/dflemstr/rq))

Setting this `docs` feature would allow the library to "defuse" itself, by not running a build script or not trying to link a native library.

**Comment by onur** [comment]
This is a good idea but I was planning to add an option for `extra-features` and `no-default-features`. This is a most requested feature for docs.rs. See: #18 

Checking `docs` feature can also be useful.
