### ISSUE TITLE
help menu for doc make the whole page blur

### ISSUE THREAD

**Issue by Kerollmops** [onur/docs.rs#52]
When pressing `?` the whole page is blur, a little error in the css I supposed 😄

**Comment by onur** [comment]
Thanks for reporting.

But I am not sure when this occurs, can you give a link?

**Comment by Kerollmops** [comment]
go on this page https://docs.rs/keen/1.2.0/keen/ and press `?`

**Comment by onur** [comment]
woah thanks for reporting, I have an addon replacing `?` content thats why I never saw it. Let me investigate what is causing this blur.

**Comment by Kerollmops** [comment]
What is this addon ? 😄  And what is it for ?

**Comment by onur** [comment]
Ahh it's nothing related with rust. VimFx was replacing help content for me.

This issue is caused by this CSS rules defined in rustdoc.css:

```css
body.blur > :not(#help) {
    filter: blur(8px);
    -webkit-filter: blur(8px);
    opacity: .7;
}
```

It is adding a blur filter to every child element of `body.blur` except `#help` child. Problem is, in docs.rs help is inside `body.blur > div.rustdoc > #help`. I don't know how to override this, I hope someone can help.

**Comment by Kerollmops** [comment]
Why not using `-Z unstable-options --extend-css`.

https://blog.guillaume-gomez.fr/articles/2016-09-16+Generating+doc+with+rustdoc+and+a+custom+theme

**Comment by onur** [comment]
Well actually docs.rs is not just extending css. It is adding some navigation and moving rustdoc content to div.rustdoc. You can see it in [rustdoc.hbs](https://github.com/onur/docs.rs/blob/444ff0cb43d915cf0c212a56812e51440cf42172/templates/rustdoc.hbs). I don't think `--extend-css` will make any difference.

**Comment by Kerollmops** [comment]
Can we just erase this rule:
```
body.blur > :not(#help) {
    filter: blur(8px);
    -webkit-filter: blur(8px);
    opacity: .7;
}
```

by this one:
```
div.rustdoc.blur > :not(#help) {
    filter: blur(8px);
    -webkit-filter: blur(8px);
    opacity: .7;
}
```

and erase the previous rule: http://stackoverflow.com/questions/15901030/reset-remove-css-styles-for-element-only

This is ugly, no ?

**Comment by Kerollmops** [comment]
In fact that's the javascript script !
It touch the DOM and add the `.blur` class to the `body` element.

**Comment by onur** [comment]
@Kerollmops your rule worked with a little bit workaround, thanks again!

**Comment by Kerollmops** [comment]
Great :+1:
