### ISSUE TITLE
Update rust nightly

### ISSUE THREAD

**Issue by svenstaro** [onur/docs.rs#54]
It appears my package can't be compiled because of the outdated version of rust nightly. I checked the logs [here](https://docs.rs/crate/bvh/0.0.0/builds/31021) and someone in IRC suggested this was due to nightly being old.

**Comment by onur** [comment]
I'll update `rustc` but clippy is almost always working with a specific version of nightly. You may want to change your clippy dependency and use an alternate way to use it.
