### ISSUE TITLE
Idea: Show small badge to jump to newest version

### ISSUE THREAD

**Issue by bluss** [onur/docs.rs#57]
Imagine you're browsing the slightly outdated docs of some project: https://docs.rs/regex/0.1.75/regex/

There could be a small badge that's visible in that case (maybe yellow or orange) that lets you jump to the current version (“Version 0.1.77 is the most recent release”).

It's important for this feature that the badge is not shown if you're already at the newest release.

Versioned links are going to be very useful, but this could be a small help if you have users arrive to stale docs via old links without them being aware of it.

**Comment by onur** [comment]
This is an awesome idea.

But where should I put this badge? Any suggestions?

And do you think docs.rs badges are enough? i.e: regex crate: ![regex](https://docs.rs/regex/badge.svg)

**Comment by bluss** [comment]
Something self-explanatory, like ![image](http://i.imgur.com/8vwdyoo.png)

**Comment by onur** [comment]
TBH this kinda looks ugly to me: ![shields.io-example](https://img.shields.io/badge/most%20recent%20version-0.1.77-orange.svg)

**Comment by bluss** [comment]
Location:

I was thinking it wants to be on every single documentation page, not just the crate root (again thinking of the case when you arrive through some external link or old bookmark). Maybe top right corner, above the Platform selector and the description? (Looking at this page as a random example [(page)](https://docs.rs/regex/0.1.75/regex/trait.Replacer.html))

**Comment by bluss** [comment]
I doesn't have to be those particular "badges". Just text with some background color to make it stand out just a small amount.

**Comment by onur** [comment]
I see.

Let me see what I can do without breaking page's minimalistic style and default look and feel.

**Comment by onur** [comment]
This is what I got after few tries, I think it looks cool:

[![docs.rs](https://i.imgur.com/da2cxJk.png)](https://i.imgur.com/da2cxJk.png)

**Comment by bluss** [comment]
Yeah that looks great

**Comment by Yamakaky** [comment]
Maybe more "Last version" than "Recent version". Or maybe something "you are seeing an outdated version, here to see the last"

**Comment by onur** [comment]
Since we got #58 I am planning to show only version number and a dropdown menu to all versions and if version isn't the latest version I will show it orange.

**Comment by bluss** [comment]
This is a crucial feature since old crate versions’ docs are placed high on google already.

**Comment by onur** [comment]
Since I introduced new navigation for rustdocs, it is more easy to add this warning. What do you think about this kind of warning? @bluss @Yamakaky 

![zzz](https://cloud.githubusercontent.com/assets/345828/24196484/9fc22368-0f06-11e7-9465-8da1233099a8.png)

**Comment by bluss** [comment]
That looks perfect!

**Comment by bluss** [comment]
New narrower docs.rs header is very good, too.

**Comment by bluss** [comment]
Thanks a lot for implementing this!
