### ISSUE TITLE
Idea: quick dropdown menu to switch between versions

### ISSUE THREAD

**Issue by dashed** [onur/docs.rs#58]
It wasn't immediately obvious on how to switch between versions of docs until switching it via the "Crates" tab.

Hence, I think it might be more convenient to switch between versions via a dropdown menu. This dropdown menu may be placed next to the "Platform" dropdown menu.

**Comment by onur** [comment]
I think we can improve #57 and add all versions as a dropdown menu.

**Comment by dashed** [comment]
Yeah I saw that issue and wanted to suggest the 'version dropdown menu' idea in that issue; but instead opted to create a new one. 😄

**Comment by bluss** [comment]
I think it's important to remember to make it stand out using color or otherwise, when the docs are not the latest version.
