### ISSUE TITLE
Can you update the rust nightly every night?

### ISSUE THREAD

**Issue by svenstaro** [onur/docs.rs#62]
We have a project that follows along rust nightly in a very rolling fashion and sometimes we depend on rust nightly being a certain minimum version. As such, it would be nice if docs.rs could also always have the respective newest rust nightly.

**Comment by svenstaro** [comment]
The failing build in question is [this](https://docs.rs/crate/bvh/0.1.0) but the point is that this will reoccur often.

**Comment by onur** [comment]
I am planning periodic nightly upgrades (need to update cargo first) but you should really consider using clippy as a optional dependency.

**Comment by onur** [comment]
I believe this issue is fixed. Periodic rustc updates maybe a thing in future.
