### ISSUE TITLE
Hidden supporting code in documentation is shown

### ISSUE THREAD

**Issue by mindriot101** [onur/docs.rs#71]
The ["Documentation" documentation][documentation] states that supporting code in examples within documentation can be hidden from rendering, but run when code examples are treated as tests. This is achieved by prefixing the supporting hidden code with "#".

For my crate [`fitsio`][fitsio] the hidden supporting code is rendered along with the example. This is what my second example example block looks like on [`docs.rs`][docs.rs]:

![fitsio_0_3_0_-_docs_rs](https://cloud.githubusercontent.com/assets/59756/19467992/1ec9e7b0-950c-11e6-8704-94cd1bf4143f.png)

whereas when I build the documentation locally it appears as such:

![fitsio_-_rust](https://cloud.githubusercontent.com/assets/59756/19468013/2c99c1ee-950c-11e6-8d58-817504d603b9.png)

Is this related to the fact that my crate does not build? My crate is a wrapper around a reasonably niche astronomy package [`cfitsio`][cfitsio] and such I did not consider it worth requesting as a standard dependency, as it's user base is fairly limited. I note that in #23 it [is mentioned that custom dependency support is planned to be added to the manifest file][5] - in which case I'm happy to wait.

[documentation]: https://doc.rust-lang.org/book/documentation.html#documentation-as-tests
[fitsio]: https://docs.rs/crate/fitsio/
[docs.rs]: https://docs.rs
[cfitsio]: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
[5]: https://github.com/onur/docs.rs/issues/23#issuecomment-242946162

**Comment by onur** [comment]
Thanks for reporting. I installed missing `libcfitsio` dependency and `fitsio` is building fine now.

Hidden codes in markdown is a rustdoc extension and doesn't work in README's.

**Comment by mindriot101** [comment]
> Thanks for reporting. I installed missing libcfitsio dependency and fitsio is building fine now.

Thanks for this, I wasn't expecting you to go to this trouble!

> Hidden codes in markdown is a rustdoc extension and doesn't work in README's

Ah yes, I'll link to the correct page now in the crates.

Thanks for the fast response!

**Comment by mindriot101** [comment]
I notice my crates to not have their own `README` files. Can I get a clarification: the main page (with the "documentation" tab) shows the crate documentation - as per `cargo doc`. Does the crate page then try to find a readme and falls back to the crate documentation if absent?

**Comment by mindriot101** [comment]
@onur I'm happy to close this issue - my crates now have stub README's which point to the main documentation and they are all rendering correctly

**Comment by onur** [comment]
@mindriot101 that is great.

BTW I forgot to answer your question. Docs.rs is currently looking for `readme` field in `Cargo.toml` and if `Cargo.toml` doesn't contain any `readme`, it is showing rustdoc from root of crate. I will improve README detection (#42). Most of the crates have README's but they are not defined in Cargo.toml.

Closing this issue.
