### ISSUE TITLE
Have a way that crates.io could tell if a crate has successfully built docs on docs.rs

### ISSUE THREAD

**Issue by carols10cents** [onur/docs.rs#87]
This is what's blocking rust-lang/crates.io#459. 

> I personally think that at least one major blocker for this will be to not generate a link for crates which have documentation that failed to build on docs.rs. That may unfortunately provide a pretty sub-par experience :(

Is there currently an automated, definitive way that crates.io could check to see if docs.rs has built docs successfully? 

If there isn't currently a way to do this, I'm trying to imagine what the best way would be, for both sides. 

Crates.io can't check on crate publish and store that data, since docs.rs can't build docs for crates it doesn't know are published yet 😂😂😂 So I guess it would be better to check when crates.io is rendering a crate show page... but we can't request a docs.rs URL with AJAX since that's cross-domain. 

Is there a way to make the docs.rs badge not render if the docs haven't built?

**Comment by onur** [comment]
docs.rs is currently rendering a red badge if build fails. I believe it is a useful feature, allowing people to see if their docs have any issue or not.

I have a better idea, I can add a simple end point with [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin) header, so crates.io can send AJAX requests and check if docs.rs built the docs.
